spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: jwat-server
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "090224T@n"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080
  servlet:
    context-path: /jwat-server

app:
  cors:
    allowed-origins: http://localhost:5173
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400 # a day
      refresh-token:
        expiration: 604800 # a week


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

